routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Frontend\DashboardController as FrontendDashboardController;
use App\Http\Controllers\Frontend\GalleryController as FrontendGalleryController;
use App\Http\Controllers\Frontend\KontakController as FrontendKontakController;
use App\Http\Controllers\Frontend\ProdukController as FrontendProdukController;
use App\Http\Controllers\Frontend\TentangController as FrontendTentangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('visitor')->group(function() {

    Route::get('/', [FrontendDashboardController::class,'index'])->name('dashboard');

    Route::post('/', [FrontendDashboardController::class, 'store'])->name('feedback-front');

    Route::get('/produk', [FrontendProdukController::class,'index'])->name('produk');

    Route::get('/produk/detail-produk/{slug}', [FrontendProdukController::class,'detail'])->name('detail-produk');

    Route::get('/gallery', [FrontendGalleryController::class,'index'])->name('gallery');

    Route::get('/tentang', [FrontendTentangController::class,'index'])->name('tentang');

    Route::get('/kontak', [FrontendKontakController::class,'index'])->name('kontak');
});




Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::get('/',[HomeController::class,'index'])->name('home');

        Route::resource('/profile',UserController::class);

        Route::resource('/produk',ProdukController::class);

        Route::resource('/gallery',GalleryController::class);

        Route::resource('/dashboard',DashboardController::class);

        Route::resource('/feedback',FeedbackController::class);

    });
});



// Route::resource('riwayat','RiwayatController');

// Route::resource('admin', 'UsersController')
//     ->middleware('auth');
// Route::group(['middleware' => 'auth'], function () {

// });

require __DIR__.'/auth.php';

app/Models/Produk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Produk extends Model
{
    use HasFactory;

    protected $table = 'produk';
}

app/Http/Controllers/Frontend/ProdukController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Produk;
use App\Models\Gallery;
use App\Models\Dashboard;

class ProdukController extends Controller
{
    public function index()
    {
        $this->param['produk'] = Produk::all();
        $this->param['gallery'] = Gallery::all();
        $this->param['dashboard'] = Dashboard::first();

        return view('frontend.pages.produk.index', $this->param);
    }

    public function detail($slug)
    {
        $this->param['produk'] = Produk::select('produk.id_produk', 'produk.nama', 'produk.harga', 'produk.gambar','produk.deskripsi', 'produk.kategori', 'produk.slug', 'produk.status')->where('produk.slug', $slug)->first();
        $this->param['oproduk'] = Produk::inRandomOrder()->limit(3)->get();
        $this->param['gallery'] = Gallery::all();
        $this->param['dashboard'] = Dashboard::first();

        return view('frontend.pages.produk.detail', $this->param);
    }
}

app/Http/Controllers/ProdukController.php
<?php

namespace App\Http\Controllers;

use App\Models\Produk;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class ProdukController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $produk = Produk::all();
        return view('backend.produk.index')->with('produk', $produk)->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->param['subtitle'] = 'Tambah Produk';
        $this->param['top_button'] = route('produk.index');

        return view('backend.produk.create', $this->param);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nama'=>'required|min:6',
            'harga'=>'required|numeric',
            'gambar'=>'required',
            'deskripsi'=>'required',
            'kategori'=>'required|not_in:0',
            'status'=>'required|not_in:0',
        ],
        [
            'required' => 'Harap isi :attribute',
            'deskripsi.required' => 'Isi Deskripsi',
            'min' => 'Panjang karakter minimal 6',
        ],
        [
            'nama' => 'Nama Produk',
            'harga' => 'Harga Produk',
            'gambar' => 'Gambar Produk',
            'deskripsi' => 'Deskripsi Produk',
            'kategori' => 'Kategori Produk',
            'status' => 'Status Produk'
        ]
        );
        try{
            $data = array(
                'nama' => $request->get('nama'),
                'harga' => $request->get('harga'),
                'deskripsi' => $request->get('deskripsi'),
                'kategori' => $request->get('kategori'),
                'status' => $request->get('status'),
                'slug' => Str::slug($request->get('nama'))
            );
            $lastId = DB::table('produk')->insertGetId($data, 'id_produk');

            if($request->file('gambar') != null) {
                $folder = 'upload/produk/'.$request->get('gambar');
                $file = $request->file('gambar');
                $filename = date('YmdHis').$file->getClientOriginalName();
                $path = realpath($folder);
                if (!($path !== true AND is_dir($path))) {
                    mkdir($folder, 0755, true);
                }
                if ($file->move($folder, $filename)) {
                    DB::table('produk')->where('id_produk', '=', $lastId)->update([
                        'gambar' => $folder.$filename
                    ]);
                }
            }

            return redirect('administrator/produk')->withStatus('Berhasil menambah data');
        }
        catch(\Exception $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Produk $produk)
    {
        return view('backend.produk.index',compact('produk'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($produk)
    {
        $produk = Produk::where('id_produk', $produk)->first();
        return view('backend.produk.edit',compact('produk'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_produk)
    {
        $request->validate([

        ]);
        try{
            $foto = Produk::where('id_produk', $id_produk)->first()->gambar;
            DB::table('produk')->where('id_produk', $id_produk)->update([
            'nama' => $request->get('nama'),
            'harga' => $request->get('harga'),
            'deskripsi' => $request->get('deskripsi'),
            'kategori' => $request->get('kategori'),
            'status' => $request->get('status'),
            'slug' => Str::slug($request->get('nama'))
        ]);
            if($request->file('gambar') != null) {
                $folder = 'upload/produk/'.$request->get('gambar');
                $file = $request->file('gambar');
                $filename = date('YmdHis').$file->getClientOriginalName();
                $path = realpath($folder);
                if (!($path !== true AND is_dir($path))) {
                    mkdir($folder, 0755, true);
                }
                if(file_exists($foto)){
                    if(File::delete($foto)){
                        if ($file->move($folder, $filename)) {
                            DB::table('produk')->where('id_produk', '=', $id_produk)->update([
                                'gambar' => $folder.$filename
                            ]);
                        }
                    }
                }

            }
            return redirect()->route('produk.index')->with('Berhasil', 'Data Produk berhasil Diubah');
        }
        catch(\Exception $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id_produk)
    {
        try{
            $foto = Produk::where('id_produk', $id_produk)->first()->gambar;
            if($foto != null){
                if(file_exists($foto)){
                    if(File::delete($foto)){
                        DB::table('produk')->where('id_produk', $id_produk)->delete();
                    }
                }
            }
            return redirect()->route('produk.index')->with('Berhasil', 'Data Produk berhasil Dihapus');

        }
        catch(\Exception $e){
            return $e->getMessage();
            //return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return $e->getMessage();
            //return redirect()->back()->withError($e->getMessage());
        }
    }
}

resources/views/backend/produk/create.blade.php
@extends('layouts.template')
@section('content')
    @if ($errors->any())
        <div class=" alert alert-danger">
            <strong>Whoops!</strong> Terdapat kesalahan pada input anda.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid p-0">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-3"><strong>Produk</strong></h1>
                <a href="{{ route('produk.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                        class="fas fa-download fa-sm text-white-50"></i>Lihat Semua Data</a>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h4 class="m-0 font-weight-bold text-primary">Input Produk</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('produk.store') }}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="form-group">
                                    <label for="nama">Nama Produk</label>
                                    <input type="text" class="form-control mb-3" id="nama"
                                        placeholder="Masukkan Nama Produk" name="nama">
                                    @error('nama')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="harga">Harga Produk</label>
                                    <input class="form-control mb-3" type="number" step="any" class="form-control"
                                        id="harga" name="harga" placeholder="Masukkan Harga Produk"
                                        onkeypress="return hanyaAngka(event)">
                                </div>
                                <div class=" form-group">
                                    <label for="gambar">Gambar Produk</label>
                                    <input type="file" class="form-control-file mb-3" id="gambar" name="gambar">
                                </div>
                                <div class="form-group">
                                    <label for="deskripsi">Deskripsi Produk</label>
                                    <textarea type="text" class="form-control mb-3" rows="2" id="deskripsi" name="deskripsi"
                                        placeholder="Masukkan Deskripsi Produk"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="kategori">Kategori</label>
                                    <select class="form-select mb-3" id="kategori" name="kategori">
                                        <option selected value="0">Pilih Kategori</option>
                                        <option value="Tanaman">Tanaman</option>
                                        <option value="Alat">Alat</option>
                                        <option value="Produk Olahan">Produk Olahan</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select class="form-select mb-3" id="status" name="status">
                                        <option selected value="0">Pilih Status</option>
                                        <option value="Tersedia">Tersedia</option>
                                        <option value="Tidak Tersedia">Tidak Tersedia</option>
                                    </select>
                                </div>
                                <input type="submit" value="simpan" class="btn btn-primary"></td>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/backend/produk/edit.blade.php
@extends('layouts.template')
@section('content')
    @if ($errors->any())
        <div class=" alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid p-0">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-3"><strong>Produk</strong></h1>
                <a href="{{ route('produk.index') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                        class="fas fa-download fa-sm text-white-50"></i>Lihat Semua Data</a>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h4 class="m-0 font-weight-bold text-primary">Edit Produk</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('produk.update', $produk->id_produk) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="nama">Nama Produk</label>
                                    <input type="text" class="form-control mb-3" id="nama" value="{{ $produk->nama }}"
                                        name="nama">
                                </div>
                                <div class="form-group">
                                    <label for="harga">Harga produk</label>
                                    <input type="number" class="form-control mb-3" id="harga" name="harga"
                                        value="{{ $produk->harga }}">
                                </div>
                                <div class="form-group">
                                    <label for="deskripsi">Deskripsi produk</label>
                                    <textarea type="text" class="form-control mb-3" id="deskripsi" name="deskripsi">{{ $produk->deskripsi }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="gambar">Gambar produk</label>
                                    <input type="file" class="form-control-file mb-3" id="gambar" name="gambar"
                                        value="{{ $produk->gambar }}"><br>
                                    <div class="d-flex align-items-start mb-3">
                                        <img width="100px" height="100px" src="{{ url('' . $produk->gambar) }}"
                                            alt=" {{ $produk->name }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="kategori">Kategori</label>
                                    <select class="form-select mb-3" name="kategori" id="kategori"
                                        class="form-control @error('kategori') is-invalid @enderror">
                                        <option value="Tanaman" @if (old('type', $produk->kategori) === 'Tanaman') selected @endif>Tanaman
                                        </option>
                                        <option value="Alat" @if (old('type', $produk->kategori) === 'Alat') selected @endif>Alat
                                        </option>
                                        <option value="Produk Olahan" @if (old('type', $produk->kategori) === 'Produk Olahan') selected @endif>
                                            Produk Olahan
                                        </option>
                                    </select>
                                    @error('kategori')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <div class="form-group">
                                    <label for="status">Status</label>
                                    <select class="form-select mb-3" name="status" id="status"
                                        class="form-control @error('status') is-invalid @enderror">
                                        <option value="Tersedia" @if (old('type', $produk->status) === 'Tersedia') selected @endif>Tersedia
                                        </option>
                                        <option value="Tidak Tersedia" @if (old('type', $produk->status) === 'Tidak Tersedia') selected @endif>
                                            Tidak Tersedia
                                        </option>
                                    </select>
                                    @error('status')
                                        <div class="invalid-feedback">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                                <input type="submit" value="simpan" class="btn btn-primary"></td>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/backend/produk/index.blade.php
@extends('layouts.template')
@section('content')
    <section class="content">
        <div class="container-fluid p-0">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-3"><strong>Produk</strong></h1>
                <a href="{{ route('produk.create') }}" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i
                        class="fas fa-download fa-sm text-white-50"></i> + Tambah Data Baru</a>
            </div>
            <!-- Main content -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h4 class="m-0 font-weight-bold text-primary">Data Produk</h4>
                        </div>
                        <div class="card-body">
                            @if ($message = Session::get('Berhasil'))
                                <div class="alert alert-success">
                                    <p>{{ $message }}</p>
                                </div>
                            @endif
                            <div class="table-responsive">
                                <table id="dataTable" class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>Nama Produk</th>
                                            <th>Harga Produk</th>
                                            <th>Gambar Produk</th>
                                            <th>Deskripsi Produk</th>
                                            <th>Kategori</th>
                                            <th>Status</th>
                                            <th>Aksi</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach ($produk as $item)
                                            <tr>
                                                <td>{{ $loop->iteration }}</td>
                                                <td>{{ $item->nama }}</td>
                                                <td class="text-right">Rp. {{ number_format($item->harga, 2) }}</td>
                                                <td>
                                                    <a data-toggle="modal" class="showDetailData"
                                                        data-target=".modal-show-detail"
                                                        data-image=" {{ url('' . $item->gambar) }}">
                                                        <img src="{{ url('' . $item->gambar) }}"
                                                            alt=" {{ $item->name }}" width="200" height="200">
                                                    </a>
                                                    {{ $item->name }}
                                                </td>
                                                <td>{{ $item->deskripsi }}</td>
                                                <td> {{ $item->kategori }} </td>
                                                <td> {{ $item->status }}</td>
                                                <td>
                                                    <div class="d-flex">
                                                        <div>
                                                            <a href="{{ route('produk.edit', $item->id_produk) }}"
                                                                class="btn btn-success mr-2" title="Edit"
                                                                data-toggle="tooltip">
                                                                <i class="align-middle" data-feather="edit"></i> <span
                                                                    class="align-middle"></span> </a>

                                                        </div>
                                                        <div class="px-2">
                                                            <form
                                                                action="{{ route('produk.destroy', $item->id_produk) }}"
                                                                method="POST">
                                                                @csrf
                                                                @method('delete')
                                                                <button type="button" class="btn btn-danger" title="Hapus"
                                                                    data-toggle="tooltip"
                                                                    onclick="confirm('{{ __('Apakah anda yakin ingin menghapus ?') }}')? this.parentElement.submit() : ''">
                                                                    <i class="align-middle" data-feather="trash-2"></i>
                                                                    <span class="align-middle"></span>
                                                                </button>
                                                            </form>

                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection