routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Frontend\DashboardController as FrontendDashboardController;
use App\Http\Controllers\Frontend\GalleryController as FrontendGalleryController;
use App\Http\Controllers\Frontend\KontakController as FrontendKontakController;
use App\Http\Controllers\Frontend\ProdukController as FrontendProdukController;
use App\Http\Controllers\Frontend\TentangController as FrontendTentangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('visitor')->group(function() {

    Route::get('/', [FrontendDashboardController::class,'index'])->name('dashboard');

    Route::post('/', [FrontendDashboardController::class, 'store'])->name('feedback-front');

    Route::get('/produk', [FrontendProdukController::class,'index'])->name('produk');

    Route::get('/produk/detail-produk/{slug}', [FrontendProdukController::class,'detail'])->name('detail-produk');

    Route::get('/gallery', [FrontendGalleryController::class,'index'])->name('gallery');

    Route::get('/tentang', [FrontendTentangController::class,'index'])->name('tentang');

    Route::get('/kontak', [FrontendKontakController::class,'index'])->name('kontak');
});




Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::get('/',[HomeController::class,'index'])->name('home');

        Route::resource('/profile',UserController::class);

        Route::resource('/produk',ProdukController::class);

        Route::resource('/gallery',GalleryController::class);

        Route::resource('/dashboard',DashboardController::class);

        Route::resource('/feedback',FeedbackController::class);

    });
});



// Route::resource('riwayat','RiwayatController');

// Route::resource('admin', 'UsersController')
//     ->middleware('auth');
// Route::group(['middleware' => 'auth'], function () {

// });

require __DIR__.'/auth.php';

app/Models/Dashboard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dashboard extends Model
{
    use HasFactory;

    protected $table = 'dashboard';
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Dashboard;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dashboard = Dashboard::first();
        return view('backend.dashboard.edit')->with('dashboard', $dashboard)->with('i',(request()->input('page',1)-1)*5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Dashboard $dashboard)
    {
        return view('backend.dashboard.edit',compact('dashboard'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dashboard = Dashboard::first();
        return view('backend.dashboard.edit',compact('dashboard'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id_dashboard)
    {
        $request->validate([
            'nama'=>'required|min:6',
            'alamat'=>'required',
            'deskripsi'=>'required',
            'whatsapp'=>'required|regex:/^([0-9\s\-\+\(\)]*)$/|min:10',
        ],
        [
            'required' => 'Harap isi :attribute',
            'deskripsi.required' => 'Isi Deskripsi',
            'min' => 'Panjang karakter minimal 6',
        ],
        [
            'nama' => 'Nama Produk',
            'alamat' => 'alamat Produk',
            'deskripsi' => 'Deskripsi Produk',
            'whatsapp' => 'whatsapp Produk'
        ]
        );
        try{
            $foto = Dashboard::first()->logo;
            DB::table('dashboard')->update([
            'nama' => $request->get('nama'),
            'alamat' => $request->get('alamat'),
            'deskripsi' => $request->get('deskripsi'),
            'whatsapp' => $request->get('whatsapp'),

        ]);
            if($request->file('logo') != null) {
                $folder = 'upload/dashboard/'.$request->get('logo');
                $file = $request->file('logo');
                $filename = date('YmdHis').$file->getClientOriginalName();
                $path = realpath($folder);
                if (!($path !== true AND is_dir($path))) {
                    mkdir($folder, 0755, true);
                }
                if(file_exists($foto)){
                    if(File::delete($foto)){
                        if ($file->move($folder, $filename)) {
                            DB::table('dashboard')->update([
                                'logo' => $folder.$filename
                            ]);
                        }
                    }
                } else{
                    if ($file->move($folder, $filename)) {
                            DB::table('dashboard')->update([
                                'logo' => $folder.$filename
                            ]);
                        }
                }
            }

            return redirect()->route('dashboard.index')->with('Berhasil', 'Data Dashboard berhasil Diubah');
        }
        catch(\Exception $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Frontend/DashboardController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Dashboard;
use App\Models\Gallery;
use App\Models\Feedback;
use App\Models\Post;


class DashboardController extends Controller
{

    public function show(Post $post)
    {
        $post->visitsCounter()->increment();

        return view('post.show', ['post' => $post]);
    }

    public function add(Post $post) {
        $post = Post::first();

        visits($post)->period('day')->count();
        visits($post)->period('week')->count();
        visits($post)->period('month')->count();
        visits($article)->countries();
        visits($article)->refs();
        visits($article)->operatingSystems();
        visits($article)->languages();
    }

    public function index()
    {
        $this->param['dashboard'] = Dashboard::first();
        $this->param['agallery'] = Gallery::inRandomOrder()->limit(5)->get();
        $this->param['ogallery'] = Gallery::inRandomOrder()->limit(3)->get();

        return view('dashboard', $this->param);
    }

    public function store(Request $request)
    {
        // return $request;
        $this->validate($request,
            [
                'nama_depan' => 'required',
                'nama_belakang' => 'required',
                'saran' => 'required',
                'email' => 'required',

            ],
            [
                'required' => ':attribute harap diisi.',
                'min' => ':attribute tidak boleh lebih dari 10 karakter',
            ],
            [
                'nama_depan' => 'Nama Depan',
                'nama_belakang' => 'Nama Belakang',
                'saran' => 'Saran',
                'email' => 'Email'

            ]
        );



        try {
            $newFeedback = new Feedback;
            $newFeedback->nama_depan = $request->nama_depan;
            $newFeedback->nama_belakang = $request->nama_belakang;
            $newFeedback->saran = $request->saran;
            $newFeedback->email = $request->email;
            $newFeedback->save();

            return redirect('/')->withStatus('Berhasil menyimpan data.');
        }
        catch(\Exception $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }
        catch(\Illuminate\Database\QueryException $e){
            return $e->getMessage();
            return redirect()->back()->withError($e->getMessage());
        }

    }
}

resources/views/backend/dashboard/edit.blade.php
@extends('layouts.template')
@section('content')
    @if ($errors->any())
        <div class=" alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li> {{ $error }} </li>
                @endforeach
            </ul>
        </div>
    @endif
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid p-0">
            <div class="d-sm-flex align-items-center justify-content-between mb-4">
                <h1 class="h3 mb-3"><strong>Dashboard</strong></h1>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="card shadow mb-4">
                        <div class="card-header py-3">
                            <h4 class="m-0 font-weight-bold text-primary">Data Dashboard</h4>
                        </div>
                        <div class="card-body">
                            <form action="{{ route('dashboard.update', $dashboard->id_dashboard) }}" method="POST"
                                enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="form-group">
                                    <label for="nama">Nama</label>
                                    <input type="text" class="form-control mb-3" id="nama" value="{{ $dashboard->nama }}"
                                        name="nama" placeholder="Harap diisi dengan Nama dengan benar" required>
                                </div>
                                <div class="form-group">
                                    <label for="alamat">Alamat</label>
                                    <input type="text" class="form-control mb-3" id="alamat"
                                        value="{{ $dashboard->alamat }}" name="alamat"
                                        placeholder="Harap diisi dengan Alamat dengan benar contoh : https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3950.8557921272936!2d113.8707379147795!3d-8.013803594228966!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x60ec956105b54ae5!2zOMKwMDAnNDkuNyJTIDExM8KwNTInMjIuNSJF!5e0!3m2!1sid!2sid!4v1653060137830!5m2!1sid!2sid"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label for="logo">Logo</label>
                                    <input type="file" class="form-control-file mb-3" id="logo" name="logo"
                                        value="{{ $dashboard->logo }}"><br>
                                    <div class="d-flex align-items-start mb-3">
                                        <img width="100px" height="100px" src="{{ url('' . $dashboard->logo) }}"
                                            alt=" {{ $dashboard->name }}">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label for="deskripsi">Deskripsi</label>
                                    <textarea type="text" class="form-control mb-3" id="deskripsi" placeholder="Harap diisi dengan deskripsi dengan benar"
                                        name="deskripsi" required>{{ $dashboard->deskripsi }}</textarea>
                                </div>
                                <div class="form-group">
                                    <label for="whatsapp">Nomer Whatsapp</label>
                                    <input type="number" class="form-control mb-3" id="whatsapp" name="whatsapp"
                                        value="{{ $dashboard->whatsapp }}"
                                        placeholder="Harap di isi dengan nomer whatsapp dengan benar dan Harus di awali dengan Angka 62 contoh : 6282244112791"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label for="instagram">Link Instagram</label>
                                    <input type="text" class="form-control mb-3" id="instagram" name="instagram"
                                        value="{{ $dashboard->instagram }}"
                                        placeholder="Harap di isi link profile instagram dengan benar contoh : https://www.instagram.com/syair_devinci/"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label for="twitter">Link Twitter</label>
                                    <input type="text" class="form-control mb-3" id="twitter" name="twitter"
                                        value="{{ $dashboard->twitter }}"
                                        placeholder="Harap di isi link profile twitter dengan benar contoh : https://twitter.com/SyairV"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label for="facebook">Link Facebook</label>
                                    <input type="text" class="form-control mb-3" id="facebook" name="facebook"
                                        value="{{ $dashboard->facebook }}"
                                        placeholder="Harap di isi link profile facebook dengan benar contoh : https://www.facebook.com/Mitra-Jamur-Bondowoso-593256841159383"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label for="youtube">Link Youtube</label>
                                    <input type="text" class="form-control mb-3" id="youtube" name="youtube"
                                        value="{{ $dashboard->youtube }}"
                                        placeholder="Harap di isi link profile youtube dengan benar contoh : https://www.youtube.com/channel/UCCLLUq6aN0wXKeabf9tRb5Q"
                                        required>
                                </div>
                                <div class="form-group">
                                    <label for="gmail">Alamat Gmail</label>
                                    <input type="text" class="form-control mb-3" id="gmail" name="gmail"
                                        value="{{ $dashboard->gmail }}"
                                        placeholder="Harap di isi link profile youtube dengan benar contoh : syairadirawan96@gmail.com"
                                        required>
                                </div>
                                <input type="submit" value="simpan" class="btn btn-primary"></td>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection