routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProdukController;
use App\Http\Controllers\GalleryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FeedbackController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Frontend\DashboardController as FrontendDashboardController;
use App\Http\Controllers\Frontend\GalleryController as FrontendGalleryController;
use App\Http\Controllers\Frontend\KontakController as FrontendKontakController;
use App\Http\Controllers\Frontend\ProdukController as FrontendProdukController;
use App\Http\Controllers\Frontend\TentangController as FrontendTentangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('visitor')->group(function() {

    Route::get('/', [FrontendDashboardController::class,'index'])->name('dashboard');

    Route::post('/', [FrontendDashboardController::class, 'store'])->name('feedback-front');

    Route::get('/produk', [FrontendProdukController::class,'index'])->name('produk');

    Route::get('/produk/detail-produk/{slug}', [FrontendProdukController::class,'detail'])->name('detail-produk');

    Route::get('/gallery', [FrontendGalleryController::class,'index'])->name('gallery');

    Route::get('/tentang', [FrontendTentangController::class,'index'])->name('tentang');

    Route::get('/kontak', [FrontendKontakController::class,'index'])->name('kontak');
});




Route::middleware(['auth'])->group(function () {
    Route::prefix('administrator')->group(function () {
        Route::get('/',[HomeController::class,'index'])->name('home');

        Route::resource('/profile',UserController::class);

        Route::resource('/produk',ProdukController::class);

        Route::resource('/gallery',GalleryController::class);

        Route::resource('/dashboard',DashboardController::class);

        Route::resource('/feedback',FeedbackController::class);

    });
});



// Route::resource('riwayat','RiwayatController');

// Route::resource('admin', 'UsersController')
//     ->middleware('auth');
// Route::group(['middleware' => 'auth'], function () {

// });

require __DIR__.'/auth.php';

resources/views/layouts/_partials/footer.blade.php
<div class="container-fluid">
    <div class="row text-muted">
        <div class="col-6 text-start">
            <p class="mb-0">
                <a class="text-muted" href="https://adminkit.io/" target="_blank"><strong>AdminKit</strong></a>
                &copy;
            </p>
        </div>
        {{-- <div class="col-6 text-end">
            <ul class="list-inline">
                <li class="list-inline-item">
                    <a class="text-muted" href="https://adminkit.io/" target="_blank">Support</a>
                </li>
                <li class="list-inline-item">
                    <a class="text-muted" href="https://adminkit.io/" target="_blank">Help
                        Center</a>
                </li>
                <li class="list-inline-item">
                    <a class="text-muted" href="https://adminkit.io/" target="_blank">Privacy</a>
                </li>
                <li class="list-inline-item">
                    <a class="text-muted" href="https://adminkit.io/" target="_blank">Terms</a>
                </li>
            </ul>
        </div> --}}
    </div>
</div>

resources/views/layouts/_partials/head.blade.php
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
<meta name="author" content="AdminKit">
<meta name="keywords"
    content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

<link rel="preconnect" href="https://fonts.gstatic.com">
<link rel="shortcut icon" href={{ asset('frontend/img/logo(1).png') }} />

<link rel="canonical" href="https://demo-basic.adminkit.io/" />

<title>Mitra Jamur Bondowoso</title>

<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<link href="{{ asset('backend/css/app.css') }}" rel="stylesheet">

resources/views/layouts/_partials/modal.blade.php
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title float-start" id="mediumModalLabel">Konfirmasi Logout ?</h5>
                <button type="button" class="btn-close float-end close" data-dismiss="modal" aria-label="Close"></button>
                {{-- <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button> --}}
            </div>
            <div class="modal-body">
                <p>
                    Pilih <strong>"Keluar" </strong> untuk keluar.
                </p>
            </div>
            <div class="modal-footer">
                <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button type="submit" class="btn btn-primary">Keluar</button>
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Batal</button>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/layouts/_partials/sidebar.blade.php
<div class="sidebar-content js-simplebar">
    <a class="sidebar-brand" href="{{ route('home') }}">
        <span class="align-middle">AdminKit</span>
    </a>

    <ul class="sidebar-nav">
        <li class="sidebar-header">
            Pages
        </li>

        <li class="sidebar-item {{ request()->segment(2) == 'home' ? 'active' : '' }}">
            <a class="sidebar-link" href="{{ route('home') }}">
                <i class="align-middle" data-feather="sliders"></i> <span class="align-middle">Home</span>
            </a>
        </li>

        <li class="sidebar-item {{ request()->segment(2) == 'produk' ? 'active' : '' }}">
            <a class="sidebar-link" href="{{ route('produk.index') }}">
                <i class="align-middle" data-feather="shopping-cart"></i> <span class="align-middle">Produk</span>
            </a>
        </li>

        <li class="sidebar-item {{ request()->segment(2) == 'gallery' ? 'active' : '' }}">
            <a class="sidebar-link" href="{{ route('gallery.index') }}">
                <i class="align-middle" data-feather="image"></i> <span class="align-middle">Gallery</span>
            </a>
        </li>

        <li class="sidebar-item {{ request()->segment(2) == 'dashboard' ? 'active' : '' }}">
            <a class="sidebar-link" href="{{ route('dashboard.edit', 1) }}">
                <i class="align-middle" data-feather="home"></i> <span class="align-middle">Dashboard</span>
            </a>
        </li>

        <li class="sidebar-item {{ request()->segment(2) == 'feedback' ? 'active' : '' }}">
            <a class="sidebar-link" href="{{ route('feedback.index') }}">
                <i class="align-middle" data-feather="inbox"></i> <span class="align-middle">Feedback</span>
            </a>
        </li>

    </ul>
</div>

resources/views/layouts/_partials/topbar.blade.php
<nav class="navbar navbar-expand navbar-light navbar-bg">
    <a class="sidebar-toggle js-sidebar-toggle">
        <i class="hamburger align-self-center"></i>
    </a>
    <div class="navbar-collapse collapse">
        <ul class="navbar-nav navbar-align">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle d-none d-sm-inline-block" data-bs-toggle="dropdown">
                    <img src="{{ asset('backend/img/avatars/avatar.jpg') }}" class="avatar img-fluid rounded me-1"
                        alt="Admin" /> <span class="text-dark">{{ auth()->user()->name }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-end">
                    <a class="dropdown-item" href="{{ route('profile.edit', auth()->user()->id) }}"
                        data-toggle="dropdown"><i class="align-middle me-1" data-feather="user"></i>
                        Profile</a>
                    <div class="dropdown-divider"></div>
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal"><i
                            class="fa fa-power-off"></i>Logout</a>

                </div>
            </li>
        </ul>
    </div>
</nav>